### ISSUE TITLE
Fix for new esp-idf versions

### ISSUE THREAD

**Issue by DieBorr** [david-asher/VL53L1-ULD-ESP#1]
Hi @david-asher , Thank you for creating this project, I have used it on my own project, it had some deprecated stuff that now is suppose to be solved, In a few days after some test I will push a commit that fixes some files if you want :) 
Regards.

**Comment by david-asher** [comment]
Hi @DieBorr , I'm delighted that you find this driver to be useful and greatly appreciate your contribution. I'm starting to work with the newer sensor VL53L4CD and will post an update when that's working.
David

**Comment by DieBorr** [comment]
#2 should fix this.
